services:
  postgres:
    container_name: nestjs-monorepo-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=nestjs-monorepo-user
      - POSTGRES_PASSWORD=nestjs-monorepo-password
      - POSTGRES_DB=nestjs-monorepo-db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: nestjs-monorepo-redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres:
  redis:
